# This file should be saved as k8s/job.yaml in your repository
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
  labels:
    app: kube-bench
spec:
  template:
    metadata:
      labels:
        app: kube-bench
    spec:
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: kube-bench
      containers:
        - name: kube-bench
          image: docker.io/aquasec/kube-bench:v0.7.1
          command: ["kube-bench"]
          # THIS IS THE CRITICAL CHANGE THAT ENABLES JSON OUTPUT
          args: ["--json"]
          volumeMounts:
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: etc-systemd
              mountPath: /etc/systemd
              readOnly: true
            - name: etc-kubernetes
              mountPath: /etc/kubernetes
              readOnly: true
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
