name: Run kube-bench Scan 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kube-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.2' # Best practice: Pin to your cluster's compatible version

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          # Try to decode the secret as Base64. If it fails, assume it's a raw string.
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config || echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Run kube-bench job
        run: |
          kubectl apply -f https://raw.githubusercontent.com/aquasecurity/kube-bench/main/job.yaml
          echo "Waiting for kube-bench job to complete..."
          kubectl wait --for=condition=complete job/kube-bench --timeout=5m

      - name: Retrieve and Save Scan Results
        run: |
          POD_NAME=$(kubectl get pods --selector=job-name=kube-bench --output=jsonpath='{.items[0].metadata.name}')
          echo "Saving results to kube-bench-results.txt"
          kubectl logs $POD_NAME > kube-bench-results.txt
          echo "Scan Results:"
          cat kube-bench-results.txt

      - name: Upload kube-bench Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: kube-bench-report
          path: kube-bench-results.txt
          retention-days: 90

