name: Syft SBOM to DefectDojo
on:
  workflow_dispatch:

jobs:
  syft-sbom-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Syft & Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM
        run: syft dir:. --exclude=./.git -o cyclonedx-json > sbom.json

      - name: Scan SBOM with Grype
        run: grype sbom:sbom.json -o json > vuln-report.json

      - name: Upload Scan Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: vuln-report.json

      - name: Upload Report to DefectDojo
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -F "file=@vuln-report.json" \
            -F "scan_type=Anchore Grype" \
            -F "engagement_name=CI-CD" \
            -F "product_name=MyProduct" \
            -F "auto_create_context=true"
