# .github/workflows/syft-grype-scan.yml
name: On-Demand Security Scan

on:
  workflow_dispatch:
    inputs:
      repo_url:
        description: 'URL of the GitHub repository to Scan'
        required: true
        default: 'juice-shop/juice-shop'

jobs:
  scan-repository:
    name: Scan External Repository
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repo_url }}

      - name: Build container image
        run: |
          docker build -t scan-target:${{ github.run_id }} .

      - name: Generate SBOM with Syft
        uses: anchore/syft-action@v0
        with:
          image: "scan-target:${{ github.run_id }}"
          format: "spdx-json"
          output: "sbom.spdx.json"

      - name: Scan image with Grype
        uses: anchore/grype-action@v0
        with:
          image: "scan-target:${{ github.run_id }}"
          fail-on-severity: "critical"
          output-format: "table,sarif,json"

      - name: Upload Grype report as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: grype-report-table
          path: grype-results.txt

      - name: Upload SARIF report to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: grype-results.sarif

      - name: Upload SBOM as Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sbom
          path: sbom.spdx.json

      # ** MODIFIED STEP **
      # The product_name and engagement_name are now hardcoded as requested.
      - name: Upload to DefectDojo
        if: always()
        run: |
          curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -F "file=@grype-results.json" \
            -F "scan_type=Grype Scan" \
            -F "product_name=MyProduct" \
            -F "engagement_name=syft-grype-sbom" \
            -F "auto_create_context=true" \
            --fail
