name: Syft SBOM to DefectDojo for Root Code
on:
  workflow_dispatch:
jobs:
  syft-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Recommended: Use the major version tag

      - name: Install Syft & Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin v0.100.0
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin v0.100.0

      - name: Generate SBOM with Syft (CycloneDX JSON)
        run: syft dir:. --exclude=./.git --exclude=./.github -o cyclonedx-json > sbom.json

      - name: Scan SBOM with Grype (JSON report)
        run: grype sbom:sbom.json -o json --by-cve > vuln-grype.json

      - name: Upload Scan Reports as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: scan-reports
          path: |
            sbom.json
            vuln-grype.json

      - name: Upload to DefectDojo
        run: |
          curl -f -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
            -F "file=@vuln-grype.json;type=application/json" \
            -F "scan_type=Anchore Grype" \
            -F "engagement_name=syft-grype-sbom" \
            -F "product_name=MyProduct" \
            -F "auto_create_context=true"
