name: Source Scan with Syft Grype to DefectDojo

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Repository to scan (e.g., juice-shop/juice-shop)'
        required: true
        default: 'juice-shop/juice-shop'

jobs:
  scan-source-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.target_repo }}
          path: './source-to-scan'

      - name: Generate SBOM from source directory
        uses: anchore/sbom-action@v0
        with:
          source: "dir:./source-to-scan"
          output-file: "sbom-source.json"

      - name: Scan SBOM with Grype and Generate SARIF Report
        id: grype-scan
        uses: anchore/scan-action@v3
        with:
          sbom: "sbom-source.json"
          fail-build: false
          output-format: sarif

      - name: Upload SARIF report as a workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: grype-sarif-report-source
          path: results.sarif
          if-no-files-found: ignore

      - name: Upload Grype Scan to DefectDojo
        if: success()
        run: |
          echo "Checking for the existence of the report file..."
          ls -la # For debugging

          if [ -f "results.sarif" ]; then
            echo "Report file 'results.sarif' found. Uploading to DefectDojo..."
            echo "Product: MyProduct"
            echo "Engagement: syft-grype-sbom"

            curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
              -H "Authorization: Token ${{ secrets.DEFECTDOJO_TOKEN }}" \
              -F "file=@results.sarif" \
              # CORRECTED: Using the format-specific parser name "SARIF".
              -F "scan_type=SARIF" \
              -F "product_name=MyProduct" \
              -F "engagement_name=syft-grype-sbom" \
              -F "verified=true" \
              -F "auto_create_context=true"
          else
            echo "Grype report file not found. Skipping upload. This usually means no vulnerabilities were detected."
          fi
